spring:
  datasource:
    url: jdbc:mysql://localhost:3306/modac?useSSL=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qkrgmldns3#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
   web:
     pageable:
       max-page-size: 10

springdoc:
  swagger-ui:
    path: /docs/swagger

jwt:
  secret-key: zcR9P80KqqLmF5hT8dQ7VzXwJJgNZp3qrTy4FcRNm8L9H2zBxPVwP7L8RcNF5G2Q3xAW9cK6d
  access-exp-time: 3600000 # 액세스 토큰 만료 시간 (밀리초 단위, 예: 1시간)
  refresh-exp-time: 60480000 # 리프레시 토큰 만료 시간