spring:
  servlet:
    multipart:
      max-file-size: 50MB       # 개별 파일 최대 크기
      max-request-size: 50MB    # 전체 요청(파일 + 폼 데이터) 최대 크기
  datasource:
    url: jdbc:mysql://localhost:3306/modac?useSSL=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qkrgmldns3#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
   web:
     pageable:
       max-page-size: 10

springdoc:
  swagger-ui:
    path: /docs/swagger


file:
  dir: /Users/usr/Documents/study/file/

jwt:
  secret-key: zcR9P80KqqLmF5hT8dQ7VzXwJJgNZp3qrTy4FcRNm8L9H2zBxPVwP7L8RcNF5G2Q3xAW9cK6d
  access-exp-time: 36000000 # 액세스 토큰 만료 시간 (밀리초 단위, 예: 1시간)
  refresh-exp-time: 604800000 # 리프레시 토큰 만료 시간

server:
  tomcat:
    max-http-header-size: 655360